version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smedia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smedia_db"]
      interval: 10s
      retries: 5

  init_db:
    build: .
    image: init_db:1.0
    command: python bot/models.py
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@db:5432/smedia_db

  main_bot:
    build: .
    image: bot:1.0
    command: python bot/main.py
    volumes:
      - .:/smedia_tt
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@db:5432/smedia_db

  scheduler_bot:
    build: .
    image: scheduler:1.0
    command: python bot/scheduler.py
    volumes:
      - .:/smedia_tt
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:password@db:5432/smedia_db

volumes:
  postgres_data:
